language: minimal

notifications:
  email: false

script:
  - docker build -t osirixfoundation/nginx-certbot:$TRAVIS_BRANCH .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push osirixfoundation/nginx-certbot:$TRAVIS_BRANCH
