language: minimal

notifications:
  email: false

script:
   - docker build -t osirixfoundation/nginx-certbot:$TRAVIS_BRANCH .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
deploy:
   - docker push osirixfoundation/nginx-certbot:$TRAVIS_BRANCH
